# config.sh — Install-state helpers for install.sh
# Sourced by install.sh. Defines: INSTALLED_TARGETS, EXTRA_CATALOGS_CLI,
# REGISTERED_NAMESPACES, REGISTERED_GROUPS, read_install_cfg, write_install_cfg,
# mark_targets, unmark_targets.

# ---------------------------------------------------------------------------
# install.cfg — records which targets are installed
# ---------------------------------------------------------------------------
# Written to .agents/principles-catalog/install.cfg so /dot-scout Phase 6 knows
# which review outputs to emit. Each line is a target ID (e.g. claude, copilot-ide).

# Read existing install.cfg into an associative array.  Returns target IDs in
# the INSTALLED_TARGETS associative array (keys = target IDs, values = "1").
declare -A INSTALLED_TARGETS
# CLI-supplied extra catalog directories (populated by arg parsing before dispatch).
EXTRA_CATALOGS_CLI=()
# Namespace and group registries used during vendor to detect conflicts.
declare -A REGISTERED_NAMESPACES
declare -A REGISTERED_GROUPS

read_install_cfg() {
    local new_cfg="$1/.agents/principles-catalog/install.cfg"
    local legacy_cfg="$1/.principles-catalog/install.cfg"
    INSTALLED_TARGETS=()
    local cfg_file=""
    if [ -f "$new_cfg" ]; then
        cfg_file="$new_cfg"
    elif [ -f "$legacy_cfg" ]; then
        cfg_file="$legacy_cfg"
    fi
    if [ -n "$cfg_file" ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            # Skip comments and blank lines
            [[ "$line" =~ ^[[:space:]]*# ]] && continue
            [[ -z "${line// /}" ]] && continue
            INSTALLED_TARGETS["$line"]="1"
        done < "$cfg_file"
    fi
}

# Write install.cfg from the INSTALLED_TARGETS associative array.
write_install_cfg() {
    local project_dir="$1"
    local cfg_dir="$project_dir/.agents/principles-catalog"
    mkdir -p "$cfg_dir"
    local cfg_file="$cfg_dir/install.cfg"
    {
        echo "# .principles install.cfg — installed targets"
        echo "# Auto-generated by install.sh — do not edit manually."
        echo "# Skills read this file to know which targets are installed."
        for target in "${!INSTALLED_TARGETS[@]}"; do
            echo "$target"
        done
    } | sort > "$cfg_file"
}

# Mark targets as installed.  Call before write_install_cfg.
mark_targets() {
    for t in "$@"; do
        INSTALLED_TARGETS["$t"]="1"
    done
}

# Remove targets.  Call before write_install_cfg.
unmark_targets() {
    for t in "$@"; do
        unset "INSTALLED_TARGETS[$t]"
    done
}
